root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ./cmd"
bin = "tmp/main"
full_bin = "dlv exec --accept-multiclient --headless --continue --listen :2345 --api-version 2 ./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "env"]
exclude_dir = ["docker", "deployments", "data", "build", "frontend"]