root = "."
tmp_dir = "tmp"

[build]
cmd = "sh bash/port.sh && CGO_ENABLED=0 go build -gcflags='all=-N -l' -buildvcs=false -o ./tmp/main ./cmd"
bin = "tmp/main"
full_bin = "dlv exec --accept-multiclient --headless --continue --listen :2345 --api-version 2 ./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "env", "js", "css"]
exclude_dir = ["docker", "deploy", "data", "build", "frontend/node_modules", "internal/repository/pg/migrations"]
